---
- name: Install Packages on AIX using the DNF utility
  hosts: aix
  become: true
  gather_facts: false
  vars:
    ansible_python_interpreter: /opt/freeware/bin/python3.9

  tasks: 

    - name: Install packages in the packages list
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: latest
        use_backend: dnf4
      loop: "{{ packages }}"
