---
- name: Add a user to the Sudoers
  hosts: aix
  gather_facts: false

  tasks:

    - name: Add a user to sudoers - FULL ACCESS
      community.general.sudoers:
        name: full-access
        state: present
        user: cnorville
        commands: ALL
        nopassword: true
