---
- name: Configure the inittab on an AIX Machine
  hosts: aix
  become: true
  gather_facts: false
  vars_files:
    - vars.yml

  tasks: 

    - name: New entry in the inittab
      ibm.power_aix.inittab:
        state: modify 
        name: uprintfd
        runlevel: '1234567'
        action: 'respawn'
        command: '/usr/sbin/uprintfd'
        insertafter: 'perfstat'
