---
- name: Test connectivity to AIX
  hosts: aix
  become: true
  gather_facts: false

  tasks: 

    - name: Ping Module - Test basic connectivity
      ping: 

    - name: Retrieve the LPAR related information
      ibm.power_aix.lpar_facts:

    - name: Print the LPAR related information
      debug:
        var: ansible_facts.lpar
