---
- name: Add users to AIX
  hosts: aix
  become: true
  gather_facts: false


  tasks: 

    - name: Add a user to an AIX system 
      ibm.power_aix.user:
        state: present
        name: "{{ aix_newuser }}"
        change_passwd_on_login: False
        password: "{{ aix_password }}"
        attributes:
          groups: "{{ group }}"

