---
- name: Install Packages on AIX using the DNF utility
  hosts: aix
  become: true
  gather_facts: false

  tasks:

    - name: Install packages in the packages list using the DNF utility
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: latest
        use_backend: dnf4
      loop: "{{ packages }}"
