---
- name: Configure the inittab on an AIX Machine
  hosts: aix
  become: true
  gather_facts: false
  vars_files:
    - vars.yml

  tasks: 

    - name: Download the FLRT utility from IBM
      ansible.builtin.unarchive:
        src: https://esupport.ibm.com/customercare/sas/f/flrt3/FLRTVC-0.8.5.zip
        dest: /usr/local/bin
        remote_src: yes
