---
- name: Download and install the flrtvc utility for AIX
  hosts: aix
  become: true
  gather_facts: false

  tasks:

    - name: Download the FLRT utility from IBM
      ansible.builtin.unarchive:
        src: https://esupport.ibm.com/customercare/sas/f/flrt3/FLRTVC-latest.zip
        dest: /opt/freeware/bin
        mode: 755
        remote_src: yes

