---
- name: Add a user to the Sudoers
  hosts: aix
  gather_facts: false

  tasks:

    - name: Allow the bob user to run any commands as alice with sudo -u alice
      community.general.sudoers:
        name: full-access
        state: present
        user: cnorville
        commands: ALL
        nopassword: true
